config/routes.rb
# == Route Map
#
# DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/deepulatha/Desktop/Desktop/Latha/GA/wdi-19/Projects/SingingFrames/singing_frames/config/environment.rb:5)
# DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/deepulatha/Desktop/Desktop/Latha/GA/wdi-19/Projects/SingingFrames/singing_frames/config/environment.rb:5)
#      Prefix Verb   URI Pattern                  Controller#Action
#        root GET    /                            session#new
#       users GET    /users(.:format)             users#index
#             POST   /users(.:format)             users#create
#    new_user GET    /users/new(.:format)         users#new
#   edit_user GET    /users/:id/edit(.:format)    users#edit
#        user GET    /users/:id(.:format)         users#show
#             PATCH  /users/:id(.:format)         users#update
#             PUT    /users/:id(.:format)         users#update
#             DELETE /users/:id(.:format)         users#destroy
#    families GET    /families(.:format)          families#index
#             POST   /families(.:format)          families#create
#  new_family GET    /families/new(.:format)      families#new
# edit_family GET    /families/:id/edit(.:format) families#edit
#      family GET    /families/:id(.:format)      families#show
#             PATCH  /families/:id(.:format)      families#update
#             PUT    /families/:id(.:format)      families#update
#             DELETE /families/:id(.:format)      families#destroy
#     invites GET    /invites(.:format)           invites#index
#             POST   /invites(.:format)           invites#create
#  new_invite GET    /invites/new(.:format)       invites#new
# edit_invite GET    /invites/:id/edit(.:format)  invites#edit
#      invite GET    /invites/:id(.:format)       invites#show
#             PATCH  /invites/:id(.:format)       invites#update
#             PUT    /invites/:id(.:format)       invites#update
#             DELETE /invites/:id(.:format)       invites#destroy
#       login GET    /login(.:format)             session#new
#             POST   /login(.:format)             session#create
#             DELETE /login(.:format)             session#destroy
#

Rails.application.routes.draw do

  # Root path
  root :to => 'session#new'

  # CRUD routes for models
  resources :users
  resources :families
  resources :invites

  #Session routes
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # For authentication
  # post 'authenticate', to: 'authentication#authenticate'

end

app/models/family.rb
# == Schema Information
#
# Table name: families
#
#  id         :integer          not null, primary key
#  name       :text
#  photo      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Family < ApplicationRecord
  # Defining relations
  has_and_belongs_to_many :users

  # For sending and receiving invitations
  has_many :invites
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]
  # before_action :check_if_admin, :only=>[:index]
  # before_action :check_if_logged_in, :only => [:index, :edit, :update, :show, :destroy]

  def index
    @families = Family.all
    render json: @families
  end

  def show
    render json: @family
  end

  def new
    @family = Family.new
  end

  def create
    @family = Family.new family_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @family.photo = req["public_id"]
    else
      # @family.photo = "http://res.cloudinary.com/dzhoxlq6z/image/upload/v1485418003/New_carousel/home2.jpg"
    end

    # respond_to do |format|
      if @family.save
        # format.html { redirect_to families_path, notice: 'Family is successfully updated.' }
        # format.json { render json: @family, status: :ok, location: @family }
        render json: @family
      else
        # format.html { render :new, notice: "Family could not be created." }
        # format.json { render json: @family.errors, status: :unprocessable_entity }
        errors = "Invalid credentials"
        render json: errors, status: :unprocessable_entity
      end
    # end
  end

  def edit
    @invite = Invite.new
  end

  def update
    # respond_to do |format|
      if @family.update family_params
        # format.html { redirect_to @family, notice: 'Family is successfully updated.' }
        # format.json { render :show, status: :ok, location: @family }
        render json: @family
      else
        # format.html { render :edit, notice: "Family could not be created." }
        # format.json { render json: @family.errors, status: :unprocessable_entity }
        errors = "Invalid credentials"
        render json: errors, status: :unprocessable_entity
      end
    # end
  end

  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_path, notice: 'Family is successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_family
    @family = Family.find(params[:id])
  end

  def family_params
    params.require(:family).permit(:name, :photo)
  end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.erb
<%= form_for( @family, :html=>{:multipart=>true} ) do |f| %>
<div class="row">

<div class="col-md-3"></div>

<div class="col-md-6">
  <div class="form-group">
    *<%= f.label :name %>
    <%= f.text_field :name, :autofocus=>true, :required => true, :class=>"form-control  textfield-border" %>
  </div>
  <div class="form-group">
    <%= f.label :photo %>
    <%= f.cl_image_upload :photo %>
  </div>
  <div class="button-center">
    <%= f.submit :class=>"btn btn-primary"%>
  </div>
</div>

<% end %>

<div class="col-md-3"></div>

</div>

app/views/families/_header.html.erb
<!-- heading -->
<tr>
  <th>Name</th>
  <th>Family photo</th>
  <th>Edit</th>
</tr>

app/views/families/_show.html.erb
<tr>
  <!-- data -->
  <td><%= family.name%></td>
  <% if !family.photo.nil? %>
    <td><%= cl_image_tag family.photo, :class=>"img-responsive table-view" %></td>
  <% end %>
  <td><%= link_to "Edit", edit_family_path(family.id), :class=>"btn btn-primary" %></td>
</tr>

app/views/families/edit.html.erb
<h1>Edit family</h1>
<% if @family.errors.any? %>
  <ol>
  <% @family.errors.full_messages.each do |msg| %>
    <li class="bg-danger"><%= msg %></li>
  <% end %>
  </ol>
<% end %>

<%= form_for @invite , :url => invites_path do |f| %>
    <%= f.hidden_field :family_id, :value => @family.id %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.submit 'Send' %>
<% end %>

<!-- <%= render :partial=>"form" %> -->

app/views/families/index.html.erb
<h1>All families</h1>
<!-- heading -->
<div class="col-md-3"></div>

<div class="col-md-6">

  <table class="table table-striped table-hover">
    <%= render :partial=>"header"%>
    <% @families.each do |family| %>
      <%= render :partial=>"show", :locals=>{family: family} %>
    <% end %>
  </table>

</div>

<div class="col-md-3"></div>

app/views/families/new.html.erb
<h1>New family</h1>
<% if @family.errors.any? %>
  <ol>
  <% @family.errors.full_messages.each do |msg| %>
    <li class="bg-danger"><%= msg %></li>
  <% end %>
  </ol>
<% end %>

<%= render :partial => "form" %>

app/views/families/show.html.erb
<h1><%= "#{@family.name}" %></h1>
<table class="table table-striped">
  <%= render :partial=>"header" %>
  <%= render :partial=>"show", locals: {family: @family} %>
</table>