config/routes.rb
# == Route Map
#
# DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/deepulatha/Desktop/Desktop/Latha/GA/wdi-19/Projects/SingingFrames/singing_frames/config/environment.rb:5)
# DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/deepulatha/Desktop/Desktop/Latha/GA/wdi-19/Projects/SingingFrames/singing_frames/config/environment.rb:5)
#      Prefix Verb   URI Pattern                  Controller#Action
#        root GET    /                            session#new
#       users GET    /users(.:format)             users#index
#             POST   /users(.:format)             users#create
#    new_user GET    /users/new(.:format)         users#new
#   edit_user GET    /users/:id/edit(.:format)    users#edit
#        user GET    /users/:id(.:format)         users#show
#             PATCH  /users/:id(.:format)         users#update
#             PUT    /users/:id(.:format)         users#update
#             DELETE /users/:id(.:format)         users#destroy
#    families GET    /families(.:format)          families#index
#             POST   /families(.:format)          families#create
#  new_family GET    /families/new(.:format)      families#new
# edit_family GET    /families/:id/edit(.:format) families#edit
#      family GET    /families/:id(.:format)      families#show
#             PATCH  /families/:id(.:format)      families#update
#             PUT    /families/:id(.:format)      families#update
#             DELETE /families/:id(.:format)      families#destroy
#     invites GET    /invites(.:format)           invites#index
#             POST   /invites(.:format)           invites#create
#  new_invite GET    /invites/new(.:format)       invites#new
# edit_invite GET    /invites/:id/edit(.:format)  invites#edit
#      invite GET    /invites/:id(.:format)       invites#show
#             PATCH  /invites/:id(.:format)       invites#update
#             PUT    /invites/:id(.:format)       invites#update
#             DELETE /invites/:id(.:format)       invites#destroy
#       login GET    /login(.:format)             session#new
#             POST   /login(.:format)             session#create
#             DELETE /login(.:format)             session#destroy
#

Rails.application.routes.draw do

  # Root path
  root :to => 'session#new'

  # CRUD routes for models
  resources :users
  resources :families
  resources :invites

  #Session routes
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # For authentication
  # post 'authenticate', to: 'authentication#authenticate'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :text
#  email           :text
#  address         :text
#  contact         :string
#  password_digest :text
#  avatar          :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  admin           :boolean
#  latitude        :float
#  longitude       :float
#

class User < ApplicationRecord
  # Defining relations
  has_and_belongs_to_many :families
  has_many :images
  has_many :posts

  # For sending and receiving invitations
  has_many :invitations, :class_name => "Invite", :foreign_key => 'recipient_id'
  has_many :sent_invites, :class_name => "Invite", :foreign_key => 'sender_id'

  # Defining validations
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  validates_confirmation_of :password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :check_if_admin, :only=>[:index]
  # before_action :check_if_logged_in, :only => [:edit, :update, :show, :destroy]

  def index
    @users = User.all
    # render json: User.includes(:families), include: ['families']
    render json: @users
  end

  def show
    # render json: @user, include: ['families']
    render json: @user
  end

  def new
    @user = User.new
    @token = params[:invite_token] #<-- pulls the value from the url query string
  end

  def create
    @user = User.new user_params

    @token = params[:invite_token]
    if @token != nil
      family =  Invite.find_by_token(@token).family #find the user group attached to the invite
      #TBA : check if the @user.email == Invite.email
      #TBA: Add :accepted field to Invite table to and allow existing users the
      #     ability to accept or deny an invitation, instead of being automatically
      #     granted access to the user group.
      #TBA: Set an expiration time on invitations and automatically destroy
      #     invitations after a certain period of time, rendering them unusable.
      @user.families.push(family) #add this user to the new user group as a member
    end

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @user.image = req["public_id"]
    else
      # @user.image = "http://res.cloudinary.com/dzhoxlq6z/image/upload/v1485418003/New_carousel/home2.jpg"
    end

    # respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        # format.html { redirect_to root_path, notice: 'User is successfully created.' }
        # format.json { render :json =>  {:status => 'ok'} }
        render json: @user
      else
        flash[:create] = "Account could not be created."
        # render :new
        errors = "Could not create user."
        render json: errors, status: :unprocessable_entity
      end
    # end
  end

  def edit
  end

  def update
    # respond_to do |format|
      if @user.update user_params
        # format.html { redirect_to @user, notice: 'User is successfully updated.' }
        # format.json { render :json, status: :ok}
        render json: @user
      else
        # format.html { render :edit }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
        errors = "Could not update user."
        render json: errors, status: :unprocessable_entity
      end
    # end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email, :address, :contact, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">

<div class="col-md-3"></div>

<div class="col-md-6">

<%= form_for( @user, :html=>{:multipart=>true} ) do |f| %>
  <% if @token != nil %>
    <%= hidden_field_tag :invite_token, @token %>
  <% end %>

  <div class="form-group">
    *<%= f.label :name %>
    <%= f.text_field :name, :autofocus=>true, :required => true, :class=>"form-control  textfield-border" %>
  </div>
  <div class="form-group">
    *<%= f.label :email %>
    <%= f.email_field :email, :required => true, :class=>"form-control textfield-border" %>
  </div>
    <%# if @user.id.nil? %>
  <div class="form-group">
    *<%= f.label :password %>
    <%= f.password_field :password, :required => true, :class=>"form-control textfield-border" %>
  </div>
  <div class="form-group">
    *<%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :required=>true, :class=>"form-control textfield-border" %>
  </div>
  <%# end %>
  <div class="form-group">
    <%= f.label :contact %>
    <%= f.text_field :contact, :class=>"form-control textfield-border"%>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, :class=>"form-control textfield-border" %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.cl_image_upload :avatar %>
  </div>
  <!-- <div class="form-group">
      *<%= f.label :family %>
      <%= f.collection_select :family_ids, Family.all, :id, :name, :multiple => true, :prompt => 'Select'%>
  </div> -->

  <div class="button-center">
    <%= f.submit :class=>"btn btn-primary"%>
  </div>
<% end %>

</div>

<div class="col-md-3"></div>

</div>

app/views/users/_header.html.erb
<!-- heading -->
<tr>
  <th>Name</th>
  <th>Email</th>
  <th>Contact number</th>
  <th>Address</th>
  <th>Edit</th>
</tr>

app/views/users/_show.html.erb
<tr>
  <!-- data -->
  <td><%= user.name%></td>
  <td><%= user.email%></td>
  <% if !user.contact.nil? %>
    <td><%= user.contact%></td>
  <% end %>
  <% if !user.address.nil? %>
    <td><%=user.address%>
  <% end %>
  <td><%= link_to "Edit", edit_user_path(user.id), :class=>"btn btn-primary" %></td>
</tr>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<% if @user.errors.any? %>
  <ol>
  <% @user.errors.full_messages.each do |msg| %>
    <li class="bg-danger"><%= msg %></li>
  <% end %>
  </ol>
<% end %>
<%= render :partial=>"form" %>

app/views/users/index.html.erb
<h1>All users</h1>
<!-- heading -->
<table class="table table-striped table-hover">
  <%= render :partial=>"header"%>
  <% @users.each do |user| %>
    <%= render :partial=>"show", :locals=>{user: user} %>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>New user sign up</h1>
<% if @user.errors.any? %>
  <ol>
  <% @user.errors.full_messages.each do |msg| %>
    <li class="bg-danger"><%= msg %></li>
  <% end %>
  </ol>
<% end %>

<%= render :partial => "form" %>

app/views/users/show.html.erb
<h1><%= "#{@user.name}" %></h1>
<table class="table table-striped">
  <%= render :partial=>"header" %>
  <%= render :partial=>"show", locals: {user: @user} %>
</table>